import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'uk' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  uk: {
    // Navigation
    'nav.dashboard': 'Панель керування',
    'nav.properties': 'Об\'єкти',
    'nav.reports': 'Звіти',
    'nav.users': 'Користувачі',
    'nav.settings': 'Налаштування',
    'nav.logout': 'Вийти',
    
    // Auth
    'auth.login': 'Увійти',
    'auth.register': 'Реєстрація',
    'auth.email': 'Електронна пошта',
    'auth.password': 'Пароль',
    'auth.confirmPassword': 'Підтвердіть пароль',
    'auth.fullName': 'Повне ім\'я',
    'auth.forgotPassword': 'Забули пароль?',
    'auth.noAccount': 'Немає акаунту?',
    'auth.hasAccount': 'Вже є акаунт?',
    'auth.createAccount': 'Створити акаунт',
    'auth.loginTitle': 'Вхід до системи',
    'auth.registerTitle': 'Реєстрація в системі',
    'auth.welcome': 'Ласкаво просимо',
    'auth.subtitle': 'CRM для агентства нерухомості',
    'auth.hero_text': 'Керуйте об\'єктами нерухомості, відстежуйте угоди та створюйте звіти в одному місці.',
    'auth.stats_properties': 'Об\'єктів',
    'auth.stats_deals': 'Угод',
    'auth.stats_volume': 'Об\'єм',
    'auth.loginDescription': 'Увійдіть до свого акаунту для продовження',
    'auth.or': 'або',
    'auth.loginGoogle': 'Увійти з Google',
    'auth.registerGoogle': 'Зареєструватися з Google',
    'auth.joinTeam': 'Приєднуйтесь до команди',
    'auth.registerHeroText': 'Створіть акаунт та почніть працювати з потужною CRM для агентства нерухомості.',
    'auth.feature_properties': 'Управління об\'єктами нерухомості',
    'auth.feature_clients': 'Відстеження клієнтів та угод',
    'auth.feature_security': 'Безпечне зберігання даних',
    'auth.registerDescription': 'Створіть акаунт для початку роботи',
    'auth.passwordMismatch': 'Паролі не співпадають',
    'auth.passwordTooShort': 'Пароль повинен містити мінімум 6 символів',
    'auth.registerSuccess': 'Реєстрація успішна! Перевірте пошту для верифікації. Після підтвердження email, ваш акаунт має бути схвалений адміністратором.',
    'auth.fullNamePlaceholder': 'Іван Іванов',
    'account.pendingConfirmation': 'Очікується підтвердження',
    'account.pendingConfirmationMessage': 'Ваш акаунт очікує підтвердження від адміністратора. Будь ласка, зачекайте.',
    'dashboard.myProperties': 'Мої обʼєкти',
    'dashboard.allProperties': 'Всі обʼєкти',
    'dashboard.conversion': 'Конверсія лідів',
    'dashboard.funnel': 'Воронка угод',
    'dashboard.automation': 'Автоматизація',
    'dashboard.automationDescription': 'Підготовлені шаблони email-кампаній і автоматичні follow-up для клієнтів підключаються через інтеграції (Google/SMTP/Webhook). У топ-менеджерів додатково доступні розподіл лідів, призначення задач і контроль документів по угодах.',
    'properties.quickSearch': 'Швидкий глобальний пошук',
    'properties.searchPlaceholder': 'Адреса, ID об\'єкта, телефон власника...',
    'properties.priceFrom': 'Ціна від',
    'properties.priceTo': 'Ціна до',
    'properties.advancedFilter': 'Розширений фільтр',
    'properties.operationType': 'Тип операції',
    'properties.allOperations': 'Всі операції',
    'properties.sale': 'Продаж',
    'properties.rent': 'Оренда',
    'properties.newBuild': 'Новобудова',
    'properties.allCategories': 'Всі категорії',
    'properties.apartment': 'Квартира',
    'properties.house': 'Будинок',
    'properties.commercial': 'Комерція',
    'properties.land_plot': 'Земельна ділянка',
    'properties.other': 'Інше',
    'properties.allStatuses': 'Всі статуси',
    'properties.active': 'Активний',
    'properties.archived': 'Архів',
    'properties.resetFilters': 'Скинути фільтри',
    'properties.noPhotos': 'Немає фото',
    'properties.price_label': 'Ціна',
    'properties.typeCategory': 'Тип / Категорія',
    'properties.roomsArea': 'Кімнат / Площа',
    'properties.district_label': 'Мікрорайон',
    'properties.sqm': 'м²',
    'clients.title': 'Клієнтська база',
    'clients.searchPlaceholder': 'Пошук по ПІБ/контактам',
    'clients.allSegments': 'Всі сегменти',
    'clients.buyer': 'Покупець',
    'clients.seller': 'Продавець',
    'clients.tenant': 'Орендар',
    'clients.newClient': 'Новий клієнт',
    'clients.fullName': 'ПІБ',
    'clients.phone': 'Телефон',
    'clients.email': 'Email',
    'clients.add': 'Додати',
    'clients.dragTags': 'Drag-and-drop теги:',
    'clients.tag_urgent': 'терміново',
    'clients.tag_exclusive': 'ексклюзив',
    'clients.tag_no_agent': 'без посередників',
    'clients.tag_mortgage': 'іпотека',
    'clients.segment': 'Сегмент',
    'clients.ageBudget': 'Вік / Бюджет',
    'clients.interactions': 'Історія взаємодій',
    'clients.noNotes': 'Нотаток немає',
    'deals.title': 'Воронка угод',
    'deals.add': 'Додати угоду',
    'deals.stage_lead': 'Лід',
    'deals.stage_viewing': 'Перегляд',
    'deals.stage_offer': 'Пропозиція',
    'deals.stage_deal': 'Угода',
    'deals.stage_closed': 'Закрито',
    'deals.moveNext': 'Перевести на наступний етап',
    'deals.topManagerNote': 'Топ-менеджер: доступне призначення агентів, аудит історії угод і перевірка документів.',
    'deals.newDealTitle': 'Нова угода',
    'calendar.title': 'Календар та Завдання',
    'calendar.newEvent': 'Нова подія',
    'calendar.placeholder': 'Перегляд / зустріч / дедлайн',
    'calendar.syncGoogle': 'Синхр. Google Calendar (stub)',
    'calendar.add': 'Додати',
    'calendar.weeklyView': 'Тижневий вид',
    'calendar.monthlyView': 'Місячний вид / нагадування',
    'calendar.reminder1': 'Push/email нагадування підключаються через Cloudflare Workers + cron.',
    'calendar.reminder2': 'Інтеграція Google Calendar: OAuth + API sync worker.',
    'calendar.reminder3': 'Кольорові події: meeting/viewing/deadline (мінімалістичний UI).',
    'notes.title': 'Завдання',
    'notes.newTask': 'Нове завдання',
    'notes.add': 'Додати',
    'notes.active': 'Активні',
    'notes.completed': 'Виконані',
    'property.back': 'Назад',
    'property.new': 'Новий об\'єкт нерухомості',
    'property.operation': 'Тип операції',
    'property.category': 'Категорія',
    'property.status': 'Статус',
    'property.source': 'Джерело',
    'property.district': 'Мікрорайон',
    'property.street': 'Вулиця',
    'property.building': 'Будинок',
    'property.block': 'Корпус',
    'property.rooms': 'Кімнат',
    'property.area_total': 'Площа загальна (м²)',
    'property.area_living': 'Площа житлова (м²)',
    'property.area_kitchen': 'Площа кухні (м²)',
    'property.floor': 'Поверх',
    'property.floors_total': 'Поверхів у будинку',
    'property.apartment': 'Квартира №',
    'property.condition': 'Стан',
    'property.heating': 'Опалення',
    'property.bathroom': 'Санвузол',
    'property.balcony': 'Балкон / лоджія / тераса',
    'property.price': 'Ціна',
    'property.currency': 'Валюта',
    'property.price_sqm': 'Ціна за м²',
    'property.negotiable': 'Торг',
    'property.additional_costs': 'Додаткові витрати',
    'property.owner_name': 'ПІБ власника',
    'property.owner_phones': 'Телефони власника (через кому)',
    'property.coords': 'Координати (широта/довгота)',
    'property.tags': 'Теги',
    'property.owner_notes': 'Примітки щодо власника',
    'property.agent_notes': 'Нотатки агента (внутрішні)',
    'property.client_id': 'ID клієнта',
    'property.deal_id': 'ID угоди',
    'property.description': 'Опис',
    'property.photos': 'Фото об\'єкта (до 30 зображень)',
    'property.upload_prompt': 'Натисніть або перетягніть фото сюди',
    'property.upload_hint': 'Підтримуються формати: JPG, PNG, WebP',
    'property.uploaded_count': 'Завантажено',
    'property.create': 'Створити',
    'property.success_create': 'Об\'єкт успішно створено',
    'property.error_create': 'Помилка створення об\'єкта',
    'property.success_upload': 'Завантажено {count} фото',
    'property.error_upload': 'Помилка завантаження фото',
    'property.no_repair': 'Без ремонту',
    'property.cosmetic': 'Косметичний',
    'property.euro': 'Євроремонт',
    'property.furnished': 'З меблями',
    'property.after_build': 'Після будови',
    'property.central': 'Централізоване',
    'property.autonomous': 'Автономне',
    'property.electric': 'Електро',
    'property.gas': 'Газ',
    'property.separate': 'Роздільний',
    'property.combined': 'Суміжний',
    'property.balcony_item': 'Балкон',
    'property.loggia': 'Лоджія',
    'property.terrace': 'Тераса',
    'property.yes': 'Так',
    'property.no': 'Ні',
    'property.owner_src': 'Власник',
    'property.database_src': 'База',
    'property.partner_src': 'Партнер',
    'property.edit_title': 'Редагування об\'єкта',
    'property.name': 'Назва',
    'property.area': 'Площа',
    'property.owner_phones_label': 'Телефони власника',
    'property.map_title': 'Координати та карта',
    'property.my_location': 'Моя геолокація',
    'property.lat': 'Широта',
    'property.lng': 'Довгота',
    'property.success_update': 'Об\'єкт успішно оновлено',
    'property.error_update': 'Помилка оновлення об\'єкта',
    'users.subtitle': 'Керування користувачами системи',
    'users.searchPlaceholder': 'Пошук користувачів...',
    'users.approved': 'Підтверджено',
    'users.pending': 'Очікує',
    'users.pending_approval': 'Очікує підтвердження',
    'users.changeRole': 'Змінити роль',
    'users.approve': 'Підтвердити',
    'users.notFound': 'Користувачів не знайдено',
    'users.changeRoleTitle': 'Змінити роль користувача',
    'users.success_approve': 'Користувача підтверджено',
    'users.error_approve': 'Помилка підтвердження',
    'users.success_role': 'Роль оновлено',
    'users.error_role': 'Помилка оновлення ролі',
    'users.success_delete': 'Користувача видалено',
    'users.error_delete': 'Помилка видалення користувача',
    'users.delete_confirm': 'Ви впевнені, що хочете видалити цього користувача?',
    'users.role_restriction': 'Ви можете призначати тільки роль менеджера',
    'users.createDescription': 'Створіть новий акаунт для менеджера',
    'users.fullNamePlaceholder': 'Ім\'я та прізвище',
    'users.passwordHint': 'Мінімум 6 символів',
    'users.fillAllFields': 'Заповніть всі поля',
    'users.success_create': 'Користувача створено успішно!',
    'users.error_create': 'Помилка створення користувача',
    'reports.subtitle': 'Звіти та Аналітика',
    'reports.days_7': '7 днів',
    'reports.days_30': '30 днів',
    'reports.days_90': '90 днів',
    'reports.export': 'Експорт PDF/Excel (stub)',
    'reports.deals_count': 'Кількість угод',
    'reports.sales_period': 'Продажі за період',
    'reports.efficiency': 'Ефективність / тренд',
    'reports.conversion': 'Конверсія',
    
    // Dashboard
    'dashboard.title': 'Панель керування',
    'dashboard.welcome': 'Вітаємо',
    'dashboard.totalProperties': 'Всього об\'єктів',
    'dashboard.activeListings': 'Активні оголошення',
    'dashboard.closedDeals': 'Закриті угоди',
    'dashboard.recentActivity': 'Остання активність',
    'dashboard.thisMonth': 'Цього місяця',
    'dashboard.thisWeek': 'Цього тижня',
    
    // Properties
    'properties.title': 'Об\'єкти нерухомості',
    'properties.add': 'Додати об\'єкт',
    'properties.edit': 'Редагувати',
    'properties.delete': 'Видалити',
    'properties.search': 'Пошук об\'єктів...',
    'properties.filter': 'Фільтр',
    'properties.all': 'Всі',
    'properties.address': 'Адреса',
    'properties.owner': 'Власник',
    'properties.ownerName': 'ПІБ власника',
    'properties.ownerPhone': 'Телефон власника',
    'properties.description': 'Опис',
    'properties.type': 'Тип нерухомості',
    'properties.dealType': 'Тип угоди',
    'properties.price': 'Ціна',
    'properties.status': 'Статус',
    'properties.photos': 'Фотографії',
    'properties.link': 'Посилання',
    'properties.importLink': 'Імпортувати з посилання',
    'properties.importPlaceholder': 'Вставте посилання з OLX або DomRia',
    'properties.import': 'Імпортувати',
    'properties.closingAmount': 'Сума закриття',
    'properties.dateFrom': 'З дати',
    'properties.dateTo': 'По дату',
    
    // Property Types
    'property.land': 'Земельна ділянка',
    'property.office': 'Офіс',
    
    // Deal Types
    'deal.sale': 'Продаж',
    'deal.rent': 'Оренда',
    
    // Statuses
    'status.available': 'Доступний',
    'status.sold': 'Продано',
    'status.rented': 'Здано',
    'status.notSold': 'Не продано',
    'status.notRented': 'Не здано',
    
    // Reports
    'reports.title': 'Звіти',
    'reports.create': 'Створити звіт',
    'reports.weekly': 'Щотижневий',
    'reports.monthly': 'Щомісячний',
    'reports.period': 'Період',
    'reports.addedProperties': 'Додані об\'єкти',
    'reports.closedCases': 'Закриті кейси',
    'reports.totalAmount': 'Загальна сума',
    'reports.sign': 'Підписати та відправити',
    'reports.signed': 'Підписано',
    'reports.pending': 'Очікує',
    'reports.manager': 'Менеджер',
    'reports.date': 'Дата',
    
    // Users
    'users.title': 'Користувачі',
    'users.add': 'Додати користувача',
    'users.edit': 'Редагувати',
    'users.delete': 'Видалити',
    'users.role': 'Роль',
    'users.superuser': 'Суперкористувач',
    'users.top_manager': 'Топ-менеджер',
    'users.manager': 'Агент',
    'users.secretKey': 'Секретний ключ',
    'users.createdAt': 'Створено',
    
    // Common
    'common.save': 'Зберегти',
    'common.cancel': 'Скасувати',
    'common.confirm': 'Підтвердити',
    'common.loading': 'Завантаження...',
    'common.error': 'Помилка',
    'common.success': 'Успішно',
    'common.noData': 'Немає даних',
    'common.actions': 'Дії',
    'common.view': 'Переглянути',
    'common.uah': 'грн',
    'common.usd': '$',
  },
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.properties': 'Properties',
    'nav.reports': 'Reports',
    'nav.users': 'Users',
    'nav.settings': 'Settings',
    'nav.logout': 'Logout',
    
    // Auth
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.fullName': 'Full Name',
    'auth.forgotPassword': 'Forgot password?',
    'auth.noAccount': 'Don\'t have an account?',
    'auth.hasAccount': 'Already have an account?',
    'auth.createAccount': 'Create Account',
    'auth.loginTitle': 'Sign In',
    'auth.registerTitle': 'Create Account',
    'auth.welcome': 'Welcome',
    'auth.subtitle': 'Real Estate Agency CRM',
    'auth.hero_text': 'Manage properties, track deals, and create reports in one place.',
    'auth.stats_properties': 'Properties',
    'auth.stats_deals': 'Deals',
    'auth.stats_volume': 'Volume',
    'auth.loginDescription': 'Sign in to your account to continue',
    'auth.or': 'or',
    'auth.loginGoogle': 'Sign in with Google',
    'auth.registerGoogle': 'Register with Google',
    'auth.joinTeam': 'Join the Team',
    'auth.registerHeroText': 'Create an account and start working with a powerful CRM for real estate agencies.',
    'auth.feature_properties': 'Property Management',
    'auth.feature_clients': 'Client & Deal Tracking',
    'auth.feature_security': 'Secure Data Storage',
    'auth.registerDescription': 'Create an account to get started',
    'auth.passwordMismatch': 'Passwords do not match',
    'auth.passwordTooShort': 'Password must be at least 6 characters long',
    'auth.registerSuccess': 'Registration successful! Check your email for verification. After confirming your email, your account must be approved by an administrator.',
    'auth.fullNamePlaceholder': 'John Doe',
    'account.pendingConfirmation': 'Pending Confirmation',
    'account.pendingConfirmationMessage': 'Your account is awaiting confirmation from an administrator. Please wait.',
    'dashboard.myProperties': 'My Properties',
    'dashboard.allProperties': 'All Properties',
    'dashboard.conversion': 'Lead Conversion',
    'dashboard.funnel': 'Deal Funnel',
    'dashboard.automation': 'Automation',
    'dashboard.automationDescription': 'Ready-made email campaign templates and automatic follow-ups for clients are connected via integrations (Google/SMTP/Webhook). Top managers additionally have access to lead distribution, task assignment, and document control for deals.',
    'properties.quickSearch': 'Quick Global Search',
    'properties.searchPlaceholder': 'Address, Object ID, owner phone...',
    'properties.priceFrom': 'Price from',
    'properties.priceTo': 'Price to',
    'properties.advancedFilter': 'Advanced Filter',
    'properties.operationType': 'Operation Type',
    'properties.allOperations': 'All Operations',
    'properties.sale': 'Sale',
    'properties.rent': 'Rent',
    'properties.newBuild': 'New Build',
    'properties.allCategories': 'All Categories',
    'properties.apartment': 'Apartment',
    'properties.house': 'House',
    'properties.commercial': 'Commercial',
    'properties.land_plot': 'Land Plot',
    'properties.other': 'Other',
    'properties.allStatuses': 'All Statuses',
    'properties.active': 'Active',
    'properties.archived': 'Archived',
    'properties.resetFilters': 'Reset Filters',
    'properties.noPhotos': 'No photos',
    'properties.price_label': 'Price',
    'properties.typeCategory': 'Type / Category',
    'properties.roomsArea': 'Rooms / Area',
    'properties.district_label': 'District',
    'properties.sqm': 'm²',
    'clients.title': 'Client Database',
    'clients.searchPlaceholder': 'Search by Name/Contacts',
    'clients.allSegments': 'All Segments',
    'clients.buyer': 'Buyer',
    'clients.seller': 'Seller',
    'clients.tenant': 'Tenant',
    'clients.newClient': 'New Client',
    'clients.fullName': 'Full Name',
    'clients.phone': 'Phone',
    'clients.email': 'Email',
    'clients.add': 'Add',
    'clients.dragTags': 'Drag-and-drop tags:',
    'clients.tag_urgent': 'urgent',
    'clients.tag_exclusive': 'exclusive',
    'clients.tag_no_agent': 'no agents',
    'clients.tag_mortgage': 'mortgage',
    'clients.segment': 'Segment',
    'clients.ageBudget': 'Age / Budget',
    'clients.interactions': 'Interaction History',
    'clients.noNotes': 'No notes',
    'deals.title': 'Deal Funnel',
    'deals.add': 'Add Deal',
    'deals.stage_lead': 'Lead',
    'deals.stage_viewing': 'Viewing',
    'deals.stage_offer': 'Offer',
    'deals.stage_deal': 'Deal',
    'deals.stage_closed': 'Closed',
    'deals.moveNext': 'Move to Next Stage',
    'deals.topManagerNote': 'Top Manager: access to agent assignment, deal history audit, and document verification.',
    'deals.newDealTitle': 'New Deal',
    'calendar.title': 'Calendar & Tasks',
    'calendar.newEvent': 'New Event',
    'calendar.placeholder': 'Viewing / meeting / deadline',
    'calendar.syncGoogle': 'Sync Google Calendar (stub)',
    'calendar.add': 'Add',
    'calendar.weeklyView': 'Weekly View',
    'calendar.monthlyView': 'Monthly View / Reminders',
    'calendar.reminder1': 'Push/email reminders are connected via Cloudflare Workers + cron.',
    'calendar.reminder2': 'Google Calendar integration: OAuth + API sync worker.',
    'calendar.reminder3': 'Color events: meeting/viewing/deadline (minimalistic UI).',
    'notes.title': 'Tasks',
    'notes.newTask': 'New Task',
    'notes.add': 'Add',
    'notes.active': 'Active',
    'notes.completed': 'Completed',
    'property.back': 'Back',
    'property.new': 'New Property',
    'property.operation': 'Operation Type',
    'property.category': 'Category',
    'property.status': 'Status',
    'property.source': 'Source',
    'property.district': 'District',
    'property.street': 'Street',
    'property.building': 'Building',
    'property.block': 'Block',
    'property.apartment': 'Apartment',
    'property.rooms': 'Rooms',
    'property.area_total': 'Total Area (m²)',
    'property.area_living': 'Living Area (m²)',
    'property.area_kitchen': 'Kitchen Area (m²)',
    'property.floor': 'Floor',
    'property.floors_total': 'Total Floors',
    'property.condition': 'Condition',
    'property.heating': 'Heating',
    'property.bathroom': 'Bathroom',
    'property.balcony': 'Balcony / Loggia / Terrace',
    'property.price': 'Price',
    'property.currency': 'Currency',
    'property.price_sqm': 'Price per m²',
    'property.negotiable': 'Negotiable',
    'property.additional_costs': 'Additional Costs',
    'property.owner_name': 'Owner Name',
    'property.owner_phones': 'Owner Phones (comma separated)',
    'property.coords': 'Coordinates (lat/lng)',
    'property.tags': 'Tags',
    'property.owner_notes': 'Owner Notes',
    'property.agent_notes': 'Agent Notes (internal)',
    'property.client_id': 'Client ID',
    'property.deal_id': 'Deal ID',
    'property.description': 'Description',
    'property.photos': 'Property Photos (up to 30 images)',
    'property.upload_prompt': 'Click or drag photos here',
    'property.upload_hint': 'Supported formats: JPG, PNG, WebP',
    'property.uploaded_count': 'Uploaded',
    'property.create': 'Create',
    'property.success_create': 'Property created successfully',
    'property.error_create': 'Error creating property',
    'property.success_upload': 'Uploaded {count} photos',
    'property.error_upload': 'Error uploading photos',
    'property.no_repair': 'No Repair',
    'property.cosmetic': 'Cosmetic',
    'property.euro': 'Euro Repair',
    'property.furnished': 'Furnished',
    'property.after_build': 'After Build',
    'property.central': 'Centralized',
    'property.autonomous': 'Autonomous',
    'property.electric': 'Electric',
    'property.gas': 'Gas',
    'property.separate': 'Separate',
    'property.combined': 'Combined',
    'property.balcony_item': 'Balcony',
    'property.loggia': 'Loggia',
    'property.terrace': 'Terrace',
    'property.yes': 'Yes',
    'property.no': 'No',
    'property.owner_src': 'Owner',
    'property.database_src': 'Database',
    'property.partner_src': 'Partner',
    'property.edit_title': 'Edit Property',
    'property.name': 'Title',
    'property.area': 'Area',
    'property.owner_phones_label': 'Owner Phones',
    'property.map_title': 'Coordinates & Map',
    'property.my_location': 'My Location',
    'property.lat': 'Latitude',
    'property.lng': 'Longitude',
    'property.success_update': 'Property updated successfully',
    'property.error_update': 'Error updating property',
    'users.subtitle': 'Manage system users',
    'users.searchPlaceholder': 'Search users...',
    'users.approved': 'Approved',
    'users.pending': 'Pending',
    'users.pending_approval': 'Pending approval',
    'users.changeRole': 'Change role',
    'users.approve': 'Approve',
    'users.notFound': 'No users found',
    'users.changeRoleTitle': 'Change user role',
    'users.success_approve': 'User approved successfully',
    'users.error_approve': 'Approval error',
    'users.success_role': 'Role updated successfully',
    'users.error_role': 'Error updating role',
    'users.success_delete': 'User deleted successfully',
    'users.error_delete': 'Error deleting user',
    'users.delete_confirm': 'Are you sure you want to delete this user?',
    'users.role_restriction': 'You can only assign the manager role',
    'users.createDescription': 'Create a new account for a manager',
    'users.fullNamePlaceholder': 'First and Last Name',
    'users.passwordHint': 'Minimum 6 characters',
    'users.fillAllFields': 'Please fill in all fields',
    'users.success_create': 'User created successfully!',
    'users.error_create': 'Error creating user',
    'reports.subtitle': 'Reports & Analytics',
    'reports.days_7': '7 days',
    'reports.days_30': '30 days',
    'reports.days_90': '90 days',
    'reports.export': 'Export PDF/Excel (stub)',
    'reports.deals_count': 'Number of Deals',
    'reports.sales_period': 'Sales over period',
    'reports.efficiency': 'Efficiency / Trend',
    'reports.conversion': 'Conversion',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Welcome',
    'dashboard.totalProperties': 'Total Properties',
    'dashboard.activeListings': 'Active Listings',
    'dashboard.closedDeals': 'Closed Deals',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.thisMonth': 'This Month',
    'dashboard.thisWeek': 'This Week',
    
    // Properties
    'properties.title': 'Properties',
    'properties.add': 'Add Property',
    'properties.edit': 'Edit',
    'properties.delete': 'Delete',
    'properties.search': 'Search properties...',
    'properties.filter': 'Filter',
    'properties.all': 'All',
    'properties.address': 'Address',
    'properties.owner': 'Owner',
    'properties.ownerName': 'Owner Name',
    'properties.ownerPhone': 'Owner Phone',
    'properties.description': 'Description',
    'properties.type': 'Property Type',
    'properties.dealType': 'Deal Type',
    'properties.price': 'Price',
    'properties.status': 'Status',
    'properties.photos': 'Photos',
    'properties.link': 'Link',
    'properties.importLink': 'Import from Link',
    'properties.importPlaceholder': 'Paste link from OLX or DomRia',
    'properties.import': 'Import',
    'properties.closingAmount': 'Closing Amount',
    'properties.dateFrom': 'From Date',
    'properties.dateTo': 'To Date',
    
    // Property Types
    'property.land': 'Land',
    'property.office': 'Office',
    
    // Deal Types
    'deal.sale': 'Sale',
    'deal.rent': 'Rent',
    
    // Statuses
    'status.available': 'Available',
    'status.sold': 'Sold',
    'status.rented': 'Rented',
    'status.notSold': 'Not Sold',
    'status.notRented': 'Not Rented',
    
    // Reports
    'reports.title': 'Reports',
    'reports.create': 'Create Report',
    'reports.weekly': 'Weekly',
    'reports.monthly': 'Monthly',
    'reports.period': 'Period',
    'reports.addedProperties': 'Added Properties',
    'reports.closedCases': 'Closed Cases',
    'reports.totalAmount': 'Total Amount',
    'reports.sign': 'Sign & Send',
    'reports.signed': 'Signed',
    'reports.pending': 'Pending',
    'reports.manager': 'Manager',
    'reports.date': 'Date',
    
    // Users
    'users.title': 'Users',
    'users.add': 'Add User',
    'users.edit': 'Edit',
    'users.delete': 'Delete',
    'users.role': 'Role',
    'users.superuser': 'Superuser',
    'users.topManager': 'Top Manager',
    'users.manager': 'Manager',
    'users.secretKey': 'Secret Key',
    'users.createdAt': 'Created At',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.noData': 'No Data',
    'common.actions': 'Actions',
    'common.view': 'View',
    'common.uah': 'UAH',
    'common.usd': '$',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('crm-language');
    return (saved as Language) || 'uk';
  });

  useEffect(() => {
    localStorage.setItem('crm-language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['uk']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};